# MySQL konekcija (Render ?e je pregaziti preko env varijabli, ovo je samo za lokalni rad)
spring.datasource.url=jdbc:mysql://localhost:3306/dental_clinic?useSSL=false&serverTimezone=Europe/Belgrade&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate (Render override)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port (Render override sa SERVER_PORT)
server.port=8081

# CORS - ovo ne treba ovde, Render ?e dati vrednost, ali za svaki slu?aj stavi prazno
cors.allowed.origins=