spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.web.resources.static-locations=classpath:/static/,file:./static/
spring.web.resources.add-mappings=true
spring.mvc.static-path-pattern=/**
server.port=${PORT:8080}